/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmentone;

import java.util.Arrays;
import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {
  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }


  /**
   * Solution to first task.
   */
  public String helloThere() {
    HelloThere hello = new HelloThere();
    System.out.print("Name, Please: ");
    String name = input.nextLine();
    System.out.println(hello.hello(name));
    return name;
  }

  /**
   * Solution for the second task.
   */
  public void seconds() {
    Time time = new Time();
    System.out.print("Please enter hours, minutes and seconds: ");
    String[] num = input.nextLine().split(" ");
    int hours = Integer.parseInt(num[0]);
    int minutes = Integer.parseInt(num[1]);
    int seconds = Integer.parseInt(num[2]);
    System.out.println(time.toSeconds(seconds, minutes, hours));
  }

  /**
   * Solution for the third task.
   */
  public void imInaBand() {
    Album billie = new Album("Happier than ever", 2020, "Billie Eilish");
    System.out.print(billie.getName() + " was released in " + billie.getYear() + " by " + billie.getArtist());
  }

  /**
   * Solution for the fourth task.
   */
  public void bestAlbumsEver() {
    AlbumGenerator albumGen = new AlbumGenerator();
    Album[] albums = albumGen.generateAlbums();
    for (Album a : albums) {
      System.out.print(a.getName() + " was released in ");
      System.out.print(a.getYear() + " by ");
      System.out.print(a.getArtist());
      System.out.println();
    }
  }

  /**
   * Solution for the fifth task.
   */
  public void workingWithArrays() {
    int[] numbers = {5, 2, 6, 4, 1, 3, 7, 9, 8};
    int[] numsb = {5, 2, 6, 4, 1, 3, 7, 9, 8};
    ArrayAlgorithms arrayAlgorithms = new ArrayAlgorithms();
    System.out.println(Arrays.toString(numbers));
    System.out.println("The average is " + arrayAlgorithms.average(numbers));
    System.out.println("The largest value is " + arrayAlgorithms.maxValue(numbers));
    System.out.println("The index of the smallest value is at position " + arrayAlgorithms.minIndex(numbers));
    System.out.println("The shifted array:");
    int[] shift = arrayAlgorithms.shift(numbers);
    System.out.println(Arrays.toString(shift));
    int[] shuff = arrayAlgorithms.shuffle(numsb);
    System.out.println("Shuffeled array:");
    System.out.println(Arrays.toString(shuff));

  }

  /**
   * Starting point of the first assignment.
   *
   * @param args is not used.
   */
  public static void main(String[] args) {
    

    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific stream in the whole application
    // scanners should be closed when you are done and this also closes the underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    //  app.helloThere();

    // Task 2
    // app.seconds();

    // Task 3
    // app.imInaBand();

    // Task 4 
    //app.bestAlbumsEver();

    // Task 5
    app.workingWithArrays();

    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
